# Generated by Django 4.1.7 on 2023-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('images', models.ImageField(upload_to='')),
                ('created_dates', models.DateTimeField(auto_now_add=True)),
                ('updated_dates', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
