# Generated by Django 4.1.7 on 2023-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
        migrations.RemoveField(
            model_name='book',
            name='titles',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HORROR', 'HORROR'), ('COMEDY', 'COMEDY'), ('FANTASY', 'FANTASY'), ('THRILLER', 'THRILLER'), ('ROMAN', 'ROMAN'), ('DETECTIVE', 'DETECTIVE'), ('ADVENTURE', 'ADVENTURE'), ('DRAMATIC', 'DRAMATIC')], max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(null=True, verbose_name='Ссылка на книгу'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_dates',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_dates',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
