# Generated by Django 4.1.7 on 2023-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_descriptions_remove_book_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание книги:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HORROR', 'HORROR'), ('COMEDY', 'COMEDY'), ('FANTASY', 'FANTASY'), ('THRILLER', 'THRILLER'), ('ROMAN', 'ROMAN'), ('DETECTIVE', 'DETECTIVE'), ('ADVENTURE', 'ADVENTURE'), ('DRAMATIC', 'DRAMATIC')], max_length=100, null=True, verbose_name='Жанр:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото книги:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(null=True, verbose_name='Ссылка на книгу:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество страниц:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название книги:'),
        ),
    ]
