# Generated by Django 4.1.7 on 2023-03-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameNews',
            new_name='TVParser',
        ),
    ]
