# Generated by Django 4.1.7 on 2023-03-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rename_gamenews_tvparser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_url', models.CharField(max_length=100)),
                ('title_text', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('create_data', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TVParser',
        ),
    ]
